#!/bin/bash

set -e

PROJ=upathlib
SRC=$(pwd)/src/${PROJ}
TESTS=$(pwd)/tests


echo
echo --- running bandit ---
echo
bandit -r -lll ${SRC}
bandit -r -lll ${TESTS}

echo
echo --- running flake8 ---
echo
python -m flake8 --ignore E501,W503 ${SRC}

echo
#echo --- running mypy ---
echo
#python -m mypy --show-error-codes --disable-error-code import ${SRC}

echo
echo --- running pylint ---
echo
# python -m pylint --disable=C0103,C0114,C0115,C0116,C0301,C0303,C0305,R0903 ${SRC}
python -m pylint --disable=all ${SRC}

