#!/bin/bash

set -e

PROJ=upathlib

docker build \
    -f Dockerfile-dev \
    --build-arg PROJ=${PROJ} \
    -t ${PROJ}-dev:latest \
    .

SRC=/src/src/${PROJ}
TESTS=/src/tests

if [[ $# > 0 ]]; then
    if [[ "$1" != -i ]]; then
        >&2 echo "unknown argument '$1'"
        exit 1
    fi
    docker run \
        -it --rm \
        -v $(pwd):/src \
        --workdir /src \
        -e PYTHONPATH=/src/src \
        ${PROJ}-dev:latest \
        bash
else
    echo
    echo --- checking code ---
    echo
    docker run \
        --rm \
        -v $(pwd):/src \
        --workdir /src \
        -e PYTHONPATH=/src/src \
        ${PROJ}-dev:latest \
            /src/check-code
    echo
    echo --- running tests ---
    echo
    docker run \
        --rm \
        -v $(pwd):/src \
        --workdir /src \
        -e PYTHONPATH=/src/src \
        ${PROJ}-dev:latest \
            py.test \
                --log-cli-level info \
                --cov=/src/src/${PROJ} \
                --cov-report term-missing \
                --cov-fail-under 45 \
                /src/tests
fi
